services:
  - type: web
    name: music-app-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5050
      - key: WEB_ORIGIN
        value: https://ut-code.github.io
      - key: DATABASE_URL
        sync: false
