name: NodeJS Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  SaveNpmCache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install npm dependencies
        run: npm ci
        shell: bash

      - name: Save npm cache
        uses: actions/cache/save@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore npm cache
        uses: "actions/cache/restore@v3"
        with:
          path: "~/.npm"
          key: "${{ runner.os }}-${{ hashFiles('package-lock.json') }}"

      - name: Install npm dependencies
        run: npm ci
        shell: bash

      - name: Build
        run: npm run build
        shell: bash
